[package]
name = "grass"
version = "0.1.0"
edition = "2021"
default-run = "grass"

[lib]
name = "grass"
path = "src/lib/lib.rs"
test = true

[[bin]]
name = "grass"
path = "src/cli/main.rs"
test = true
required-features = ["cli"]

[features]
cli = ["dep:clap"]
default = ["cli"]

[dependencies]
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
dirs = "5.0.0"
toml = "0.7.2"
dialoguer = { version = "0.10.3", features = ["fuzzy-select"]}
git2 = "0.17.0"

[dependencies.clap]
version = "4.1.8"
optional = true
features = ["derive"]
